/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_PythonWrapper */

#ifndef _Included_main_PythonWrapper
#define _Included_main_PythonWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_PythonWrapper
 * Method:    categorize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_PythonWrapper_categorize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     main_PythonWrapper
 * Method:    loadModel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_PythonWrapper_loadModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
